name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build Dockerfile and push image # userで外部ファイル or 定義済みの処理を実行できる。ここではリポジトリのcheckout
        run: |
          IMAGE_NAME=test_container:${GITHUB_REF#refs/heads/} # docer imageの名前とそのタグ、${GITHUB_REF#refs/heads/}でブランチ名を取得している
          docker build ./app --tag ${IMAGE_NAME}
          docker login ghcr.io --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
          docker push ${IMAGE_NAME} yuriacats
        env:
          DOCKER_USERNAME: ${{ secrets.CI_REGISTRY_USER }} # リポジトリのsecretsとして定義した値を環境変数に渡す
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
